# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

emBLIMcpp <- function(R, K, NR, PK, beta, eta, maxiter = 100000L, tol = 1e-07, fdb = FALSE) {
    .Call('_pksCpp_emBLIMcpp', PACKAGE = 'pksCpp', R, K, NR, PK, beta, eta, maxiter, tol, fdb)
}

emGLIMcpp <- function(weights, R, W, K, NRr, PKr, betar, etar, maxiter = 1000000L, tol = 1e-07, fdb = TRUE) {
    .Call('_pksCpp_emGLIMcpp', PACKAGE = 'pksCpp', weights, R, W, K, NRr, PKr, betar, etar, maxiter, tol, fdb)
}

emIMBLIMcpp <- function(R, W, M, K, NR, PK, beta, eta, PM, maxiter = 1000L, tol = 1e-07, fdb = TRUE) {
    .Call('_pksCpp_emIMBLIMcpp', PACKAGE = 'pksCpp', R, W, M, K, NR, PK, beta, eta, PM, maxiter, tol, fdb)
}

emMissBLIMcpp <- function(Rr, Wr, Mr, Kr, NRr, PKr, etar, betar, mu0r, mu1r, maxiter = 1000L, tol = 1e-07, fdb = TRUE) {
    .Call('_pksCpp_emMissBLIMcpp', PACKAGE = 'pksCpp', Rr, Wr, Mr, Kr, NRr, PKr, etar, betar, mu0r, mu1r, maxiter, tol, fdb)
}

