# run roxygen2 if commit description contains [roxy]
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: roxygen

jobs:
  document:
    if: contains(github.event.head_commit.message, '[roxy]')
    name: roxy
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: roxygen2

      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'

      - name: commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE
          git commit -m '[automated commit] rebuild documentation using roxygen2'
          git push
